### ISSUE TITLE
Have an about window

### ISSUE THREAD

**Issue by alice-mkh** [cassidyjames/dippi#102]
if it's a GNOME app, it needs one. :)

**Comment by cassidyjames** [comment]
Ugh I hate this requirement. All the info you need is in GNOME Software! I have to add more UI to my app to tell you what you already know! 🤬

(It’s fine, I just think it’s an incredibly silly and dated concept…)

**Comment by alice-mkh** [comment]
I mean not everything is in GNOME Software. For example, Dippi has translations. Are translators credited anywhere in GNOME Software? :p
