### ISSUE TITLE
App freezes when typing a few characters.

### ISSUE THREAD

**Issue by mxmvncnt** [cassidyjames/dippi#109]
Hello, 

The app crashes after I start typing a few characters in the text fields. An example of this is I start typing the display size, and when I start typing the resolution (one or two characters), the app freezes and I have to close it. Happens on X11 with nvidia's latest proprietary drivers, i5-9400F  and 16GB, RAM on Arch linux. 

Works fine on my all-intel laptop on Wayland (ubuntu 22.10)

**Comment by cassidyjames** [comment]
@mxmvncnt I know it's been a looooong time since I was poking around the issue tracker here. Can you by chance check if this is still an issue on the latest version from Flathub?

**Comment by mxmvncnt** [comment]
I just checked, but now my PC has 3x the RAM, a different processor, Fedora and runs on Wayland but still has the same nvidia graphics. I could not reproduce the issue.

**Comment by cassidyjames** [comment]
Thanks for checking back in. We can always re-open or open a new issue if something similar crops up.
