### ISSUE TITLE
180-191 DPI not specific enough

### ISSUE THREAD

**Issue by BlobCodes** [cassidyjames/dippi#112]
While the text on the start screen states: "For HiDPI, 180-300 is ideal for desktops" - when typing in screen sizes that result in a dpi of 180-191, the application states that the pixel density is "potentially problematic".

I think that the text on the start screen is correct as 180dpi seems dense enough to me - but if that's not the case, I think the text should clarify it a bit more.

**Comment by cassidyjames** [comment]
Yeah this is similar to #113; the range is correct but the calculator also takes into account GNOME and elementary OS default settings of only enabling HiDPI scaling at 192 DPI. I could handle this range better by changing it to something like

>**Ideal with Tweaks**
>This display will default to a too-small 1× on some operating systems or desktops like GNOME and elementary OS, but should be usable by manually enabling 2× scaling.

**Comment by cassidyjames** [comment]
@BlobCodes @melix99 I've updated the logic at https://cassidyjames.com/dippi/?d=24&w=3840&h=2160&t=d to match what's coming in the next update for the Dippi app!

**Comment by melix99** [comment]
@cassidyjames Oh, nice!
