### ISSUE TITLE
Laptop version of measurement icons

### ISSUE THREAD

**Issue by cassidyjames** [cassidyjames/dippi#29]
The icon should change to a laptop if DisplayType is a laptop. To do that, I need laptop icons. 😄

**Comment by cassidyjames** [comment]
If https://github.com/elementary/icons/issues/383 happens, that's totally what this should be based on.

**Comment by micahilbery** [comment]
![device-laptop128](https://user-images.githubusercontent.com/10608836/34861411-36a558de-f72a-11e7-9b96-e3cd03807fd6.png) ![device-laptop64](https://user-images.githubusercontent.com/10608836/34861446-737882cc-f72a-11e7-8f97-ceb76aef56ce.png) ![device-laptop48](https://user-images.githubusercontent.com/10608836/34860562-f1cb6d9e-f723-11e7-8cfc-4f2ea5eb78fc.png) ![device-laptop32](https://user-images.githubusercontent.com/10608836/34860931-809cb468-f726-11e7-80a1-4a7023f659fb.png) ![device-laptop24](https://user-images.githubusercontent.com/10608836/34861129-2a2e8fb4-f728-11e7-99c0-13d26fe167d3.png) ![device-laptop16](https://user-images.githubusercontent.com/10608836/34861337-c6b6edda-f729-11e7-8b37-21ab34c04ea3.png)
I started working on them and posted the same thing over on the elementary icons issue but I'll put them here for your convenience and to mark my interest in working on this version too. Thoughts?

**Comment by cassidyjames** [comment]
Hey! Thanks for this. :smile: I think something a little more similar to the laptop image on the elementary homepage would make sense:

![notebook.jpg](https://elementary.io/images/responsive-images/notebook.jpg)

I think the key things to look at are the aspect ratio of the display (should be near 16:9), the thinness of the laptop, and the slight perspective. I know those probably won't all be possible at smaller sizes, but I think the bigger sizes could really shine like that.

**Comment by micahilbery** [comment]
![computer-notebook_128](https://user-images.githubusercontent.com/10608836/34885588-1c66fed0-f786-11e7-9ffe-e6c72d598582.png) ![computer-notebook_64](https://user-images.githubusercontent.com/10608836/34885593-1f970852-f786-11e7-8454-034ce5d6c4cf.png) ![computer-notebook_48](https://user-images.githubusercontent.com/10608836/34885598-224aa2fc-f786-11e7-8531-0c0cd87519de.png)

Something more like this?

**Comment by cassidyjames** [comment]
Dope! I really love the perspective and display on that. If I'm being picky, I might say that it still looks a _little_ chunky at the bottom. I think if it could look a little more idealized razor-thin it would be rad. but that's a nit. 

Color-wise I really like the black but I think the two-tone inside/outside is a little specific to the Dell XPS 13. I think either all black or a silver chassis might be more common/generic. But a black bezel. :ok_hand: 

Last nit: the glare on the display might be a little harsh, but I think just whatever is consistent with the elementary style is fair game here. It's hard to know out of context.

**Comment by micahilbery** [comment]
![computer-notebook-measure-diagonal](https://user-images.githubusercontent.com/10608836/34895885-37e74292-f7ad-11e7-9f57-d307a8609c6e.png) ![computer-notebook-measure-horizontal](https://user-images.githubusercontent.com/10608836/34895887-3a222ee6-f7ad-11e7-9aab-5304935e15e3.png) ![computer-notebook-measure-vertical](https://user-images.githubusercontent.com/10608836/34895888-3bd6f230-f7ad-11e7-8040-b28f6ed75b73.png)
eh?

**Comment by cassidyjames** [comment]
:ok_hand: those look slick!

**Comment by cassidyjames** [comment]
@TraumaD I'll probably rename the existing icons I'm using to something simpler… I'm thinking `display-measure-diagonal`, `display-measure-vertical`, etc. so these could be `display-measure-diagonal-notebook`, `display-measure-vertical-notebook`, etc.

It's not _super_ important since they're all gresourced in my app, but I still want to try to do something clean.
