### ISSUE TITLE
Information about flatpak version

### ISSUE THREAD

**Issue by ghost** [cassidyjames/dippi#51]
HI, i like your application, and i would like to install it using flatpak
but i don't find the application.
could you tell me ,where is dippi?
https://flathub.org/apps.html

thanks.

**Comment by cassidyjames** [comment]
@altntowin it looks like the community flathubbers haven't packaged it yet. They told me it would be available there :man_shrugging: 

I'll try and find a link for you.

**Comment by cassidyjames** [comment]
@altntowin it looks like it hasn't been merged yet. You can follow along at https://github.com/flathub/flathub/pull/226

**Comment by cassidyjames** [comment]
I updated the README to be more clear. I'm going to close this as there's nothing else for me to do here.

**Comment by ghost** [comment]
I see , ok thanks

**Comment by bilelmoussaoui** [comment]
The flatpak version is now available on flathub! @altntowin Enjoy!

**Comment by altntowin** [comment]
thanks!

**Comment by ghost** [comment]
Hi, sorry , but i didn't find the application on flathub

It seems not to be available yet.

**Comment by bilelmoussaoui** [comment]
Its already available. The website is not updated automatically. You can use GNOME software to install it

**Comment by cassidyjames** [comment]
It's available in the repository, but I guess they need to rebuild the website.
