### ISSUE TITLE
Unexpected ratio for 3440×1440

### ISSUE THREAD

**Issue by artemanufrij** [cassidyjames/dippi#55]
![screenshot from 2018-03-04 00 29 59](https://user-images.githubusercontent.com/16517095/36940455-76d7f6d2-1f43-11e8-8290-ab113e49ba3e.png)

**Comment by cassidyjames** [comment]
Hm, that'd be equivalent to 42:18, so I'm guessing there's a rounding error somewhere.

**Comment by cassidyjames** [comment]
Wait, 3440 is not divisible by 21—so this is just an example of a marketing term?? I wonder where the Switchboard plug gets the number from; if it's from the display itself, there's not a whole lot we can do besides matching close-enough aspect ratios or known resolutions (like #124). Hrm.

I'll have to think about this more!
