### ISSUE TITLE
AppImage

### ISSUE THREAD

**Issue by rugk** [cassidyjames/dippi#63]
I think for Dippi it would be great to have it as an AppImage. Because then you can just take one file and run it on any device.

As I said in https://github.com/cassidyjames/dippi/issues/56#issuecomment-373535812, this would be good when:
> Install dippi on such a machine and try it out live… 😉

So having a "portable" single executable would really suit for this use case.

**Comment by cassidyjames** [comment]
I don't think I'm going to personally devote the time and resources to figuring this out and packaging in yet another format. If someone wanted to contribute the work and it's low- to no-maintenance from me, I'd consider it. But my focus is on distributing via AppCenter.
