### ISSUE TITLE
Danielle Foré is wrongly addressed in the special thanks

### ISSUE THREAD

**Issue by Eldhrimer** [cassidyjames/dippi#96]
I just wanted to point out that in the metadata file Danielle is wrongly addressed by her old name. I know it is because it wasn't updated yet.

I'm sorry if this is not the place or way to point this out, but I didn't feel confident enough to do a pull request myself about this subject.

Cheers! 🏳️‍🌈

**Comment by cassidyjames** [comment]
Thanks, @Eldhrimer, this has been addressed.
